/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkCreateResult {
  'message' : string,
  'student' : [] | [Student],
  'success' : boolean,
}
export interface Student {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'grade' : string,
  'rollNumber' : string,
  'contactNumber' : string,
}
export interface StudentInput {
  'name' : string,
  'grade' : string,
  'rollNumber' : string,
  'contactNumber' : string,
}
export interface UserProfile { 'studentId' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[StudentInput], string>,
  'addStudents' : ActorMethod<[Array<StudentInput>], Array<BulkCreateResult>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllValidStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudentById' : ActorMethod<[string], [] | [Student]>,
  'getStudentsByGrade' : ActorMethod<[string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRollNumberDuplicate' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'studentLogin' : ActorMethod<[string, string], Student>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];