/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentInput = IDL.Record({
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'rollNumber' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'grade' : IDL.Text,
  'rollNumber' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const BulkCreateResult = IDL.Record({
  'message' : IDL.Text,
  'student' : IDL.Opt(Student),
  'success' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([StudentInput], [IDL.Text], []),
  'addStudents' : IDL.Func(
      [IDL.Vec(StudentInput)],
      [IDL.Vec(BulkCreateResult)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllValidStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentById' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRollNumberDuplicate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [Student], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentInput = IDL.Record({
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'rollNumber' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'grade' : IDL.Text,
    'rollNumber' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const BulkCreateResult = IDL.Record({
    'message' : IDL.Text,
    'student' : IDL.Opt(Student),
    'success' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([StudentInput], [IDL.Text], []),
    'addStudents' : IDL.Func(
        [IDL.Vec(StudentInput)],
        [IDL.Vec(BulkCreateResult)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllValidStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentById' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRollNumberDuplicate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [Student], []),
  });
};

export const init = ({ IDL }) => { return []; };